### ISSUE TITLE
Meeting point

### ISSUE THREAD

**Issue by gortazar** [dlopezp/release-checker#1]
This is an issue to check that we both have access to the project.

**Comment by dlopezp** [comment]
Dani was here

**Comment by gortazar** [comment]
Great!

Are you comfortable using english as the main language when developing the project? We can switch to spanish if this is going to be time-consuming.

**Comment by dlopezp** [comment]
No, no problem, sounds good

**Comment by gortazar** [comment]
Ok. Just a few questions before we start:
- Do you understand what the agile terms "Kanban", "Sprint", etc are?
- I assume you are an advanced user of AngularJS and Spring. These are the technologies you are going to use to build the project. Do you want to use your own workflow, or prefer to start using, for instance, something like [JHipster](https://jhipster.github.io/)? JHipster integrates Spring Boot applications with AngularJS by using Yeoman to generate automatically some parts of the application.

**Comment by dlopezp** [comment]
- Yes, I know the meaning of this terms
- I have a strong skills on Angular, but with Spring are some lower.
  I've never worked with JHipster, but it seems a good bootstrap for the project

**Comment by gortazar** [comment]
Ok. So I'm going to start adding some tasks to the backlog. The idea is to specify at a high level what we need to do in the backlog. Then, when some tasks become ready to be started, I'll move them to the ready status. You can start working on tasks that are available on the ready column.

I'm going to be descriptive within the tasks, but feel free to ask everything you think it's not clear enough.
